server:
  port: 8080

spring:
  application:
    name: api-gateway
  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
  cloud:
    gateway:
      discovery:
        enabled: true
        reactive:
          enabled: false
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/**

#logging:
#  level:
#    root: debug
